### ISSUE TITLE
error No module named 'app'

### ISSUE THREAD

**Issue by brinrbc** [CryptoRUSHGav/BrainChulo#10]
Hi! Thank you very much for your work! I ran into a problem, I can't figure out what to do with it:

```
(base) user@MacBook-Pro-BrainChulo % python app/main.py
Traceback (most recent call last):
  File "/Users/user/GitHub/BrainChulo/app/main.py", line 5, in <module>
    from app.conversations.document_based import DocumentBasedConversation
ModuleNotFoundError: No module named 'app'
```
the command `python app/main.py` I am writing from the same directory

**Comment by CryptoRUSHGav** [comment]
Hi @brinrbc , can you try `gradio app/main.py` instead.
I'm working on a fix as well

**Comment by CryptoRUSHGav** [comment]
for now use `gradio app/main.py` - Fix is on the way via this PR: https://github.com/CryptoRUSHGav/BrainChulo/pull/11
