### ISSUE TITLE
Error: cannot import name 'TextLoader' from 'langchain.document_loaders' 

### ISSUE THREAD

**Issue by brinrbc** [CryptoRUSHGav/BrainChulo#12]
Hi! Thank you.
I can't figure out what needs to be done, any ideas?
There is no TextLoader file at langchain.document_loaders, only  Text. I tried different names (I thought maybe instead of TextLoader the name should be Text)-nothing worked.
```
from app.conversations.document_based import DocumentBasedConversation
  File "/Users/user/GitHub/BrainChulo/app/conversations/document_based.py", line 1, in <module>
    from langchain.document_loaders import TextLoader
ImportError: cannot import name 'TextLoader' from 'langchain.document_loaders' (unknown location)
```

**Comment by CryptoRUSHGav** [comment]
did you run `pip install -r requirements.txt` before running `gradio main.py` ?

alternatively, install docker and just run `docker-compose up` from the root directory, this might be simpler.

**Comment by CryptoRUSHGav** [comment]
also, if you have further issues you should join our Discord. Link is in the README.md file

**Comment by brinrbc** [comment]
> did you run `pip install -r requirements.txt` before running `gradio main.py` ?
> 
> alternatively, install docker and just run `docker-compose up` from the root directory, this might be simpler.

Thank you for your help. So far, this has not solved the problem, as it turned out that almost everything that can be conflicts with other programs, while I will deal with this.
Thanks!
