### ISSUE TITLE
can we have a roadmap?

### ISSUE THREAD

**Issue by sawradip** [CryptoRUSHGav/BrainChulo#4]
### Can we have a roadmap?

I know this project is in very initial stage. But can way have a more clear roadmap on what are the short-term and long term goals? At least some more direction in `contributing.md`?

### More clear instruction on running model locally.
As well as though it is mentioned in this [issue](https://github.com/CryptoRUSHGav/BrainChulo/issues/2), but the `Readme.md` should contain a more clear instruction about running the model locally in api mode.

# Model choice
Is there any specific reason we are choosing Vicuna over LLama and others?

Another Suggestion, why don't we take an approach like [`llama-cpp-python`](https://github.com/CryptoRUSHGav/BrainChulo/issues/2), for the api purpose? 
To elaborate, they created a python wrapper with a similar api-structure to OpenAI api. That way, we can stay compatible to other models as well as follow a standardized structure.

**Comment by CryptoRUSHGav** [comment]
Thank you for your suggestions, @sawradip - They make sense.

I'll work on a roadmap. The first milestone to me is to either successfully make use of `llama-index` for data augmentation or find another recourse.

I would also prefer to keep the complexity of loading the model out of the project for now as it is unclear to me whether BrainChulo should become a managed memory / training extension for Oobabooga, a continuous AI with long-term memory, or a versatile tool for building opinionated chat characters.

**Comment by CryptoRUSHGav** [comment]
@sawradip I updated the README.md from your feedback: https://github.com/CryptoRUSHGav/BrainChulo/commit/ff53e37deea94277fae5aef5357bb5a394e9ece9

Closing this issue now. Thank you.
