### ISSUE TITLE
error running main.py

### ISSUE THREAD

**Issue by Chrusciki** [CryptoRUSHGav/BrainChulo#5]
```
Error generating text: {"detail":"Not Found"}
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/data/BrainChulo/main.py:27 in <module>                                                     │
│                                                                                                  │
│   24 │   VicunaLLM(), vectorstore.as_retriever())                                                │
│   25                                                                                             │
│   26 chat_history = []                                                                           │
│ ❱ 27 response = qna({"question": query_str, "chat_history": chat_history})                       │
│   28                                                                                             │
│   29 chat_history.append((query_str, response['answer']))                                        │
│   30                                                                                             │
│                                                                                                  │
...
...
...
Error generating text: {"detail":"Not Found"}
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /home/data/BrainChulo/main.py:27 in <module>                                                     │
│                                                                                                  │
│   24 │   VicunaLLM(), vectorstore.as_retriever())                                                │
│   25                                                                                             │
│   26 chat_history = []                                                                           │
│ ❱ 27 response = qna({"question": query_str, "chat_history": chat_history})                       │
│   28                                                                                             │
│   29 chat_history.append((query_str, response['answer']))                                        │
│   30                                                                                             │
│                                                                                                  │
ValidationError: 1 validation error for Generation
text
  str type expected (type=type_error.str)
  
```
  
  any idea why this is showing up?

**Comment by Chrusciki** [comment]
editing the langchain file 
`def _generate(
        self, prompts: List[str], stop: Optional[List[str]] = None
    ) -> LLMResult:
        """Run the LLM on the given prompt and input."""
        # TODO: add caching here.
        generations = []
        for prompt in prompts:
            text = self._call(prompt, stop=stop)
            generations.append([Generation(text=**str(text)**)])
        return LLMResult(generations=generations)`

was able to run the program but my return did not have a responce from the server, let me verify the server was running. 

`{'question': 'Who is the author in love with?', 'chat_history': [('Where did the author grow up?', '{}')], 'answer': '{}'}
`

**Comment by Chrusciki** [comment]
side note is INDEX_PATH intended to be in the .env file?
it also lists CHAT_API_HOST as API_HOST

**Comment by CryptoRUSHGav** [comment]
good catch on CHAT_API_HOST, I fixed it with https://github.com/CryptoRUSHGav/BrainChulo/commit/5ee360c49d957a32c901498b7d20215d4c0f14ab

What I think is happening is you are using an older version of Oobabooga's WebUI, and the response payload format has changed.
You should update it to its latest version. I've committed https://github.com/CryptoRUSHGav/BrainChulo/commit/076da92e0dfb38ca6b6cb65c00fb01f9b3020b32 to reflect the changes to the launch command I use to now start ooba.

Additionally, you should pull the latest `BrainChulo` and re-run `pip install -r requirements.txt` as I've added some libraries.

Please try the above and report back :)
